Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,34 +1,38 @@
-name: Java CI with Maven or Gradle
+name: Build with Maven or Gradle
 
 on:
-  workflow_dispatch:
-  workflow_call:
-  push:
-    branches: ['test3']
+ workflow_dispatch:
+ workflow_call:
+ push:
+   branches: ['test3']
+
+inputs:
+  build_tool:
+    description: 'Specify the build tool (Maven or Gradle)'
+    required: true
+    default: 'maven'
+    validation-pattern: '^(maven|Gradle)$'
 
 jobs:
-  read-piplineconfig:
-    uses: imsandeepreddy/Actions-Template/.github/workflows/read-pipelineconfig.yml@test3
-  build:
-    needs: [ read-piplineconfig ]
-    runs-on: ubuntu-latest
+ build:
+   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 11
-        uses: actions/setup-java@v3
-        with:
-          java-version: '11'
-          distribution: 'temurin'
-          cache: maven
-      - name: Build with Maven or Gradle
-        shell: bash
-        run: |
-          if [ ${{ needs.read-piplineconfig.outputs.build_tool }} == 'maven' ]; then
-            mvn -B package --file pom.xml
-          elif [ ${{ needs.read-piplineconfig.outputs.build_tool }} == 'Gradle' ]; then
-            ./gradlew build
-          else
-            echo "Invalid build tool specified. Please use 'Maven' or 'Gradle'."
-            exit 1
-          fi
+   steps:
+     - uses: actions/checkout@v2
+     - name: Set up JDK 11
+       uses: actions/setup-java@v3
+       with:
+         java-version: '11'
+         distribution: 'temurin'
+         cache: maven
+     - name: Build with Maven or Gradle
+       shell: bash
+       run: |
+         if [ ${{ inputs.build_tool }} == 'maven' ]; then
+           mvn -B package --file pom.xml
+         elif [ ${{ inputs.build_tool }} == 'Gradle' ]; then
+           ./gradlew build
+         else
+           echo "Invalid build tool specified. Please use 'Maven' or 'Gradle'."
+           exit 1
+         fi
